{{- if .Values.pdfConverter.enabled }}
apiVersion: v1
kind: Service
metadata:
  name: {{ include "growi.pdfConverter.fullname" . }}
  labels:
    {{- include "growi.pdfConverter.labels" . | nindent 4 }}
spec:
  type: {{ .Values.pdfConverter.service.type }}
  ports:
    - port: {{ .Values.pdfConverter.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    {{- include "growi.pdfConverter.selectorLabels" . | nindent 4 }}
{{- end }}
