apiVersion: v1
kind: Secret
metadata:
  name: {{ include "growi.fullname" . }}
  labels:
    {{- include "growi.labels" . | nindent 4 }}
type: Opaque
stringData:
  MONGO_URI: {{ include "growi.mongoUri" . | quote }}
  PASSWORD_SEED: {{ .Values.growi.passwordSeed | quote }}
  SECRET_TOKEN: {{ .Values.growi.secretToken | quote }}
